### ISSUE TITLE
exception 'NSInternalInconsistencyException', reason: 'bad screenScale 3'

### ISSUE THREAD

**Issue by northwind** [mdejong/AVRenderExample#1]
Hi @mdejong ,

AVAnimator is a great framework!! 

When I try to run this project on device iPhone6+, I got an exception: 
`2015-10-29 14:29:20.015 AVRenderExample[4407:865586] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'bad screenScale 3'`

Is there any plan to support 3x screen scale ?

Thanks,

**Comment by mdejong** [comment]
This should be addressed now.
